import * as vscode from 'vscode';
import { SpiritBirdClient } from './api/client';
import { Logger } from './utils/logger';
import { ChatViewProvider } from './panels/ChatViewProvider';

export function activate(context: vscode.ExtensionContext) {
    // 1. Initialize Logger
    Logger.initialize();
    Logger.log('Spirit Bird AICodex Extension is activating...');

    // 2. Register Webview sidebar view
    const chatProvider = new ChatViewProvider(context);
    context.subscriptions.push(
        vscode.window.registerWebviewViewProvider(
            ChatViewProvider.viewType,
            chatProvider
        )
    );
    Logger.log('Registered ChatViewProvider sidebar panel.');

    // 3. Register Command Line Trigger
    let disposable = vscode.commands.registerCommand('spirit-bird-aicodex.generateCode', async () => {
        Logger.log('Command "spirit-bird-aicodex.generateCode" invoked.');
        const editor = vscode.window.activeTextEditor;
        if (!editor) {
            Logger.warn('No active text editor found.');
            vscode.window.showInformationMessage('Please open a code file first.');
            return;
        }

        // Get configurations
        const config = vscode.workspace.getConfiguration('spiritBirdAiCodex');
        let apiKey = config.get<string>('apiKey') || '';
        let endpoint = config.get<string>('endpoint') || 'http://localhost:9000/api';
        let spaceSlug = config.get<string>('spaceSlug') || 'code-lab';

        // Interactive API Key fallback (premium user experience)
        if (!apiKey.trim()) {
            Logger.log('API key missing. Prompting user interactively.');
            const inputKey = await vscode.window.showInputBox({
                prompt: 'Enter your AICodex User Authentication Token (JWT)',
                placeHolder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
                ignoreFocusOut: true,
                password: true
            });

            if (!inputKey || !inputKey.trim()) {
                Logger.warn('Interactive API Key prompt canceled.');
                vscode.window.showErrorMessage('Spirit Bird AICodex requires a JWT token to function.');
                return;
            }

            apiKey = inputKey.trim();
            // Save to configuration (global target)
            await config.update('apiKey', apiKey, vscode.ConfigurationTarget.Global);
            Logger.log('API key updated globally.');
            vscode.window.showInformationMessage('AICodex API key configured successfully.');
        }

        // Extract prompt from selection or active line
        const selection = editor.selection;
        let promptText = editor.document.getText(selection);

        // If no active selection, fall back to current line
        if (!promptText.trim()) {
            const activeLine = editor.document.lineAt(selection.start.line);
            promptText = activeLine.text;
        }

        if (!promptText.trim()) {
            Logger.warn('Attempted to generate code with empty prompt.');
            vscode.window.showWarningMessage('Please write a prompt comment or select some text first.');
            return;
        }

        const client = new SpiritBirdClient(apiKey, endpoint, spaceSlug);

        // Run the code generation with loading progress indicator
        await vscode.window.withProgress({
            location: vscode.ProgressLocation.Notification,
            title: `Spirit Bird is thinking (${spaceSlug})...`,
            cancellable: false
        }, async () => {
            try {
                const generatedCode = await client.generateCode(promptText);

                // Insert generated code below selection/line
                await editor.edit(editBuilder => {
                    const insertPosition = selection.isEmpty 
                        ? new vscode.Position(selection.end.line + 1, 0)
                        : selection.end;
                    
                    const textToInsert = selection.isEmpty
                        ? `${generatedCode}\n`
                        : `\n${generatedCode}`;

                    editBuilder.insert(insertPosition, textToInsert);
                });

                Logger.log('Inserted generated code into active document.');
                vscode.window.setStatusBarMessage('✨ Code generated by Spirit Bird!', 5000);

            } catch (error: any) {
                Logger.error('Failed code generation via command line', error);
                vscode.window.showErrorMessage(`Spirit Bird Codex Error: ${error.message}`);
            }
        });
    });

    context.subscriptions.push(disposable);
    Logger.log('Spirit Bird AICodex Extension activation complete.');
}

export function deactivate() {
    Logger.log('Spirit Bird AICodex Extension deactivating...');
}
